### PR TITLE
Created officers collection

### PR DESCRIPTION
**Pull request by kemalfidan**
This PR adds the base for all of the officer functionality. Mainly there's addOfficer(), getOfficers(), and deleteOfficer() which handle updating the collection. There's also a dummy UI that queries the backend which I thought might be useful for whoever takes up the frontend portion for it. 

Some things that aren't related to the officers:
- Added city and state to chapter type
- getChapter renamed to getChapters

### CODE REVIEW

**Review by rluberto — APPROVED** [review]
Everything looks good to me

**Review by VishalAiely — APPROVED** [review]
Changes look good

**Review by tbatk — APPROVED** [review]
Everything looks good!

**Comment by kemalfidan** [comment]
Manually pushed to develop, will go ahead and close this pr

**Pull request closed without merging**
